// Copyright (c) 2017 Ubisoft Entertainment
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
namespace Sharpmake.Generators.Generic
{
    public partial class Ninja
    {
        public static class Template
        {
            public static class Solution
            {
                public static string Header =
@"# Generated by Sharpmake -- Do not edit !
# Type ""ninja help"" for usage help

";
                public static string ProjectsVariableElement = "subninja [projectFileName] \n";

                public static string PhonyTargets = ".PHONY: all clean help $(PROJECTS)\n\n";

                public static string AllRule = "all: $(PROJECTS)\n\n";

                public static string ProjectRuleBegin = "[projectName]: ";

                public static string ProjectRuleDependency = "[dependencyName] ";

                public static string ProjectRuleEnd =
                    "\n\t@echo \" ==== Building [projectName] ($(config)) ====\"" +
                    "\n\t@${MAKE} --no-print-directory -C [projectFileDirectory] -f [projectFileName]\n\n";

                public static string CleanRuleBegin = "clean:\n";

                public static string CleanRuleProject = "\t@${MAKE} --no-print-directory -C [projectFileDirectory] -f [projectFileName] clean\n";

                public static string CleanRuleEnd = "\n";

                public static string HelpRuleBegin =
                    "help:\n" +
                    "\t@echo \"Usage: make [config = name] [target]\"\n" +
                    "\t@echo \"\"\n" +
                    "\t@echo \"CONFIGURATIONS:\"\n";

                public static string HelpRuleConfiguration = "\t@echo \"   [optimization]\"\n";

                public static string HelpRuleTargetsBegin =
                    "\t@echo \"\"\n" +
                    "\t@echo \"TARGETS:\"\n" +
                    "\t@echo \"   all (default)\"\n" +
                    "\t@echo \"   clean\"\n";

                public static string HelpRuleTarget = "\t@echo \"   [projectName]\"\n";

                public static string HelpRuleEnd = "\n";
            }

            public static class Project
            {
                public static string Header =
@"# Generated by Sharpmake -- Do not edit !

";

                public static string ProjectConfigurationVariables =
@"
cxx        = [options.CompilerToUse]
ar         = ar
objdir     = [options.IntermediateDirectory]
targetdir  = [options.OutputDirectory]
target     = $targetdir/[options.OutputFile]
defines    = [options.Defines]
includes   = [options.Includes]
cppflags   = -MMD -MP $defines $includes
cflags     = $cppflags [options.CFLAGS]
cxxflags   = $cflags [options.CXXFLAGS]
ldflags    = [options.LibraryPaths]
libs       = [options.DependenciesLibraryFiles] [options.LibraryFiles]
resflags   = $defines $includes
lddeps     = [options.DependenciesLibraryFiles]
linkcmd    = [options.LinkCommand]

";
                public static string LinkCommandLib = "$ar -rcs $out $in";

                public static string LinkCommandExe = "$cxx -o $out $in $ldflags $resources $libs";

                public static string ProjectRulesGeneral =
@"

rule link
    command = $linkcmd

rule cpp
    command = $cxx $cxxflags -o $out -c $in
";

                public static string ObjectRule =
@"
build $objdir/[objectFile]: cpp [sourceFile]
";

                public static string LinkTarget =
@"
build $target: link [objectFiles]
";
            }
        }
    }
}
